language: java
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
test:
  post:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)